### ISSUE TITLE
can this be used with quarto?

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/BiocStyle#107]
I tried this notation in yaml header and it seemed to be ignored 
```
output:
  BiocStyle::pdf_document:
    toc: yes
    number_sections: yes
```
