### ISSUE TITLE
support for quarto theme

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocStyle#114]
As quarto vignettes become feasible, a `BiocStyle` type of styling should be provided to Bioconductors. 
I've asked Claude.ai to help me write a `biocstylesque.scss` file below:

```scss
/*-- scss:defaults --*/

// Color Palette
$bioc-primary: #1a81c2;
$bioc-secondary: #005C7A;
$bioc-text-dark: #333333;
$bioc-text-light: #556B7F;
$bioc-background: #FFFFFF;
$bioc-sidebar-bg: #F0F4F8;
$bioc-border-light: #D9E6F0;
$bioc-title-color: #87b13f;

// Typography
$font-stack-primary: "Helvetica Neue", Helvetica, Arial, sans-serif;

/*-- scss:mixins --*/
@mixin bioc-heading {
    color: $bioc-primary;
    font-weight: 500;
    border-bottom: 1px solid $bioc-border-light;
    padding-bottom: 0.3em;
    margin-top: 1.5em;
    margin-bottom: 0.8em;
}

/*-- scss:rules --*/
h1, h2, h3, h4, h5, h6 {
    @include bioc-heading;
}

h1 {
    font-size: 2em;
    border-bottom: 2px solid $bioc-primary;
    &.title { //target h1 with class title.
        color: $bioc-title-color; //apply custom color.
    }
}

h2 {
    font-size: 1.5em;
}

h3 {
    font-size: 1.3em;
}

h4 {
    font-size: 1.2em;
}

// Links
a {
    color: $bioc-primary;
    text-decoration: none;

    &:hover {
        color: darken($bioc-primary, 10%);
        text-decoration: underline;
    }
}

// Code blocks
pre, code {
    border-color: lighten($bioc-primary, 40%);
}

/*-- scss:uses --*/
// Additional customizations
```

which renders into:

![Image](https://github.com/user-attachments/assets/b9f7d5ec-3040-4587-b871-7dce9b232d82)

<sub> Using `quarto cli` version `1.8.0` </sub>
